from .LoginQuery import LoginQuery
from .RegisterQuery import RegisterQuery
from .GetUserDetailQuery import GetUserDetailQuery
from .UpdateUserQuery import UpdateUserQuery
from .LogoutQuery import LogoutQuery
from .GetNewAccessTokenQuery import GetNewAccessTokenQuery
from .ActivateUserQuery import ActivateUserQuery
from .GetAllUsersQuery import GetAllUsersQuery
from .DeactivateUserQuery import DeactivateUserQuery
from .DashboardStatsQuery import DashboardStatsQuery
from .MonthlySalesQuery import MonthlySalesQuery
from .DeleteUserQuery import DeleteUserQuery